### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by anderspitman** [Khan/hotload-server#1]
Is there supposed to be a makefile (README says `make deps` and `make`) or am I missing something?

**Comment by xymostech** [comment]
I think that the makefile was removed and was replace with other commands. You probably want `npm install` and `npm run build` instead?

**Comment by anderspitman** [comment]
Yeah that's what I ended up doing and it worked. Happy to PR the README
unless you want to just fix it real quick.

**Comment by wchargin** [comment]
Thanks, yeah! The makefile died in 4e854944085fbd9d491855bcb11ebb1e88b14b03. I'll update the README.
